# Generated by Django 5.0 on 2023-12-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0001_initial'),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='AmountTrackerID',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='GoodsTrackerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.goods_tracker'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='AmountTrackerID',
            field=models.ManyToManyField(blank=True, to='Donor.amount_tracker'),
        ),
    ]
