# Generated by Django 5.0 on 2023-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0002_remove_beneficiary_amounttrackerid_and_more'),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='GoodsTrackerID',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='GoodsTrackerID',
            field=models.ManyToManyField(blank=True, to='Donor.goods_tracker'),
        ),
    ]
