# Generated by Django 5.0 on 2023-12-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminStaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDetails',
            fields=[
                ('CashID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField(default=1.0)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DIK',
            fields=[
                ('DikID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DikType', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('education', 'Education'), ('medical', 'Medical'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('employment', 'Employment'), ('other', 'Other')], default='food', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(default='', max_length=30, unique=True)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=128)),
                ('DonationType', models.CharField(choices=[('cash', 'Cash'), ('materials', 'Materials')], max_length=10)),
                ('UserType', models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='donor', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CurrencyType', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound Sterling'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('ZAR', 'South African Rand'), ('AED', 'United Arab Emirates Dirham'), ('SGD', 'Singapore Dollar'), ('NZD', 'New Zealand Dollar'), ('HKD', 'Hong Kong Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('KRW', 'South Korean Won'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('ARS', 'Argentine Peso'), ('TRY', 'Turkish Lira'), ('EGP', 'Egyptian Pound'), ('PHP', 'Philippine Peso')], default='PHP', max_length=3)),
                ('CashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.cashdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Amount_Tracker',
            fields=[
                ('Amount_TrackerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField(default=1.0)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminStaff.adminstaff')),
                ('CurrencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.currency')),
            ],
        ),
        migrations.AddField(
            model_name='cashdetails',
            name='DonorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donor'),
        ),
        migrations.CreateModel(
            name='Goods_Tracker',
            fields=[
                ('GoodsTrackerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminStaff.adminstaff')),
                ('DonationInKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.dik')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('GDID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateofDonation', models.DateField(auto_now=True)),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donor')),
            ],
        ),
        migrations.AddField(
            model_name='dik',
            name='GDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.goodsdetails'),
        ),
    ]
