# Generated by Django 5.0 on 2023-12-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminStaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=50)),
                ('Contents', models.CharField(max_length=500)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Adminfeedbacks', to='AdminStaff.adminstaff')),
            ],
        ),
    ]
