# Generated by Django 5.0 on 2023-12-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feedback', '0001_initial'),
        ('SupportTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='TicketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DonorTicket', to='SupportTicket.supportticket'),
        ),
    ]
