# Generated by Django 5.0 on 2023-12-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=128)),
                ('Username', models.CharField(default='admin', max_length=50)),
                ('UserType', models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='admin', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
